In [ ]:
## Modified Version

In [1]:
import numpy as np
import time
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential
from tensorflow.keras import Input
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import datasets

In [2]:
#---get image data - variable and label...#
(x_train, y_train), (x_test, y_test) = datasets.fashion_mnist.load_data()

In [3]:
#---see what the variable looks like---#
print(y_train[0])  #---this is the label---#

print(x_train[0][5][22])   #--0 = sample number, 5=row, 22=column; pixel value = 247 in RGB scale upto 255---#
print(x_train[0][5])       #--0 = sample number, 5=row; array of pixel values of all 28 columns of sample 0 row 5
x_train[0]

9
0
[  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134
 144 123  23   0   0   0   0  12  10   0]


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [4]:
print(y_train.shape)
print(y_train)
y_train[48909]

(60000,)
[9 0 0 ... 3 0 5]


0

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
x_train=x_train.reshape((60000,28 * 28))  #---reshape the 3D tensor to 2D array of 60K samples and 784 features---#
x_train = x_train.astype("float32") / 255  

In [7]:
x_train[0][250]

0.8980392

In [8]:
x_test=x_test.reshape((10000,28 * 28))  #---reshape the 3D tensor to 2D array of 60K samples and 784 features---#
x_test = x_test.astype("float32") / 255  

In [9]:
y_train.shape

(60000,)

In [10]:
y_train[59999]

5

In [11]:
# convert class vectors to binary class matrices
num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

In [12]:
print(y_train.shape)
y_train[59999]

(60000, 10)


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [13]:
# model = keras.models.Sequential([keras.layers.Flatten(input_shape=[28,28]),
#                                 keras.layers.Dense(300,activation='relu'),
#                                 keras.layers.Dense(100,activation='relu'),
#                                 keras.layers.Dense(10,activation='softmax')])

In [14]:
model = Sequential()
model.add(layers.Dense(300,activation='relu',input_shape=(28 * 28,)))
model.add(layers.Dense(100,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))


In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.layers

In [17]:
hidden1=model.layers[0]
hidden1.name

'dense'

In [18]:
weights, biases = hidden1.get_weights()

In [19]:
weights.shape

(784, 300)

In [20]:
weights[0]

array([-0.04092249, -0.0548816 ,  0.07130978,  0.04008415, -0.05455458,
       -0.00226321,  0.05416594, -0.06696462,  0.01693781, -0.00753151,
       -0.02344143, -0.01229712, -0.01378611,  0.03981893, -0.00993446,
        0.01709858, -0.05450834,  0.03145903,  0.03018674, -0.01805964,
       -0.05127047, -0.05805083, -0.04782791, -0.04613261, -0.01548999,
        0.00568784,  0.00185822, -0.05999139, -0.05533024, -0.02760353,
        0.05626614,  0.04979292, -0.01868046,  0.05237697, -0.03254284,
       -0.01693688, -0.07135554, -0.01008242, -0.02153138,  0.0611559 ,
       -0.00091128,  0.05916552, -0.0031506 , -0.07027016,  0.07006308,
        0.00924678, -0.03589359,  0.0123817 , -0.04677603,  0.03934338,
       -0.01383954, -0.04768261, -0.03565796,  0.03655922, -0.03022117,
        0.05809914, -0.00945323, -0.00986033,  0.01073603, -0.06530429,
       -0.03062419, -0.03558405, -0.03361536, -0.07056729,  0.00376553,
        0.01853586,  0.01657381,  0.06355205,  0.03844856,  0.05

In [21]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [22]:
x_train.shape

(60000, 784)

In [23]:
#----Sparse categorical crossentropy loss function is used because the label data is NOT one-hot encoded----#
model.compile(loss="categorical_crossentropy", optimizer="rmsprop", metrics=["accuracy"])

In [24]:
model.fit(x_train,y_train,epochs=30,batch_size=256)

Epoch 1/30
235/235 [==============================] - 2s 4ms/step - loss: 0.8632 - accuracy: 0.7030
Epoch 2/30
235/235 [==============================] - 1s 4ms/step - loss: 0.4336 - accuracy: 0.8409
Epoch 3/30
235/235 [==============================] - 1s 4ms/step - loss: 0.3678 - accuracy: 0.8657
Epoch 4/30
235/235 [==============================] - 1s 4ms/step - loss: 0.3286 - accuracy: 0.8765
Epoch 5/30
235/235 [==============================] - 1s 4ms/step - loss: 0.3071 - accuracy: 0.8849
Epoch 6/30
235/235 [==============================] - 1s 4ms/step - loss: 0.2846 - accuracy: 0.8944
Epoch 7/30
235/235 [==============================] - 1s 4ms/step - loss: 0.2701 - accuracy: 0.8996
Epoch 8/30
235/235 [==============================] - 1s 4ms/step - loss: 0.2606 - accuracy: 0.9022
Epoch 9/30
235/235 [==============================] - 1s 4ms/step - loss: 0.2398 - accuracy: 0.9093
Epoch 10/30
235/235 [==============================] - 1s 4ms/step - loss: 0.2402 - accuracy: 0.9081

In [25]:
test_loss, test_acc = model.evaluate(x_test,y_test)
print('test accuracy = %0.2f' %test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.4608 - accuracy: 0.8939
test accuracy = 0.89
